environment:

  pypi_password:
    secure: Ccv6xibMSCG/0HwrWsekSg==

  matrix:

    # - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    # - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install --upgrade --ignore-installed setuptools"
  - "%PYTHON%\\python.exe -m pip install pytest"
  - "%PYTHON%\\python.exe -m pip install --only-binary :all: numpy cython scipy"  # we need scipy for the tests
  # install xlmhg
  - "%PYTHON%\\python.exe -m pip install -e ."
  # - "%PYTHON%\\python.exe -m pip install wheel"

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python evrsion you want to use on PATH.
  - echo "Hello World"
  - "%PYTHON%\\python.exe -m pytest tests/"
  # - %PYTHON%\\python.exe setup.py test"

after_test:
  # this step builds the wheels.
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.

