notifications:
- provider: Email
  to:
  - florian.compbio@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false

build: Script

branches:
 only:
   - master
   - develop

skip_tags: true

environment:

  pypi_password:
    secure: Ccv6xibMSCG/0HwrWsekSg==

  matrix:

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_MAJOR_VERSION: "3"
      ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_MAJOR_VERSION: "3"
      ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_MAJOR_VERSION: "3"
      ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_MAJOR_VERSION: "3"
      ARCH: "64"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"
      PYTHON_MAJOR_VERSION: "3"
      ARCH: "32"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_MAJOR_VERSION: "3"
      ARCH: "64"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8"
      PYTHON_MAJOR_VERSION: "3"
      ARCH: "32"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_MAJOR_VERSION: "3"
      ARCH: "64"


    #- PYTHON: "C:\\Python36"
    #  PYTHON_VERSION: "3.6"
    #  PYTHON_MAJOR_VERSION: "3"
    #  ARCH: "32"

    #- PYTHON: "C:\\Python36-x64"
    #  PYTHON_VERSION: "3.6"
    #  PYTHON_MAJOR_VERSION: "3"
    #  ARCH: "64"

install:
  # install numpy and cython for the Python environment
  # provided by Appveyor
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install --upgrade --ignore-installed setuptools"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install --only-binary :all: numpy cython"  # we need scipy for the tests
  - "%PYTHON%\\python.exe -m pip install -e ."

  # we need scipy to execute XL-mHG tests
  # but scipy does not provide windows binaries => use conda

  # download conda
  # bitsadmin.exe /transfer "DownloadMiniconda" https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe %cd%\\miniconda.exe
  - if "%PYTHON_MAJOR_VERSION%" == "2" (
      if "%ARCH%" == "32" (
        PowerShell.exe -ExecutionPolicy Bypass -Command "& {(New-Object System.Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe', '%cd%\\miniconda.exe')}"
      )
      else (
        PowerShell.exe -ExecutionPolicy Bypass -Command "& {(New-Object System.Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86_64.exe', '%cd%\\miniconda.exe')}"
      )
    )
    else (
      if "%ARCH%" == "32" (
        PowerShell.exe -ExecutionPolicy Bypass -Command "& {(New-Object System.Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe', '%cd%\\miniconda.exe')}"
      )
      else (
        PowerShell.exe -ExecutionPolicy Bypass -Command "& {(New-Object System.Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe', '%cd%\\miniconda.exe')}"
      )
    )
  - dir
  # install conda
  - miniconda.exe /InstallationType=JustMe /S /D=%cd%\\Miniconda
  - set "CONDA=%cd%\\Miniconda\\Scripts\\conda.exe"
  - set "ACTIVATE=%cd%\\Miniconda\\Scripts\\activate.bat"
  # configure and update conda
  - "%CONDA% config --set always_yes yes --set changeps1 yes"
  - "%CONDA% update conda"
  - "%CONDA% info -a"

  # set up conda environment
  - "%CONDA% create -n testenv python=%PYTHON_VERSION% numpy cython scipy"

  # activate conda environment
  - "%ACTIVATE% testenv"
  - pip install --upgrade pip
  - pip install --upgrade --ignore-installed setuptools
  - pip install --upgrade pytest twine
  - pip install -e .

  # install xlmhg

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python evrsion you want to use on PATH.
  - py.test tests/02_api/test_result.py
      tests/01_algorithms/test_correct_bound.py
      tests/01_algorithms/test_correct_stat.py
  # - "%PYTHON%\\python.exe -m pytest tests/"
  # - %PYTHON%\\python.exe setup.py test"

after_test:
  # this step builds the wheels.
  # uses the python binary provided by appveyor
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

on_success:
  - if "%APPVEYOR_REPO_BRANCH%" == "master" (
      twine upload -u flo-compbio -p %pypi_password% dist\*
    )
#
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.

